# Generated by Django 4.0.5 on 2022-07-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_alter_shorturl_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='slug',
            field=models.SlugField(blank=True, default='1', max_length=30),
            preserve_default=False,
        ),
    ]
