# Generated by Django 4.0.5 on 2022-07-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_alter_shorturl_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='name',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
